import type { Metadata } from "next";
import {
  Fira_Sans_Extra_Condensed,
  Poppins,
  Open_Sans,
} from "next/font/google";
import "./globals.css";
import CustomLayoutProvider from "@/Providers/CustomLayoutProvider";
import Footer from "@/Components/Footer";
import ScrollTopLink from "@/Components/Common/ScrollTopLink";
import NextTopLoader from "nextjs-toploader";

const openSans = Open_Sans({
  variable: "--font-OpenSans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const fireSans = Fira_Sans_Extra_Condensed({
  variable: "--font-fireSans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${openSans.variable} ${poppins.variable} ${fireSans.variable} font-OpenSans antialiased`}
      >
        <CustomLayoutProvider>{children}</CustomLayoutProvider>
        <ScrollTopLink />
        <Footer />
        <NextTopLoader
          color="#ffc61a"
          height={4}
          showSpinner={true}
          zIndex={1600}
        />
      </body>
    </html>
  );
}
